# Generated by Django 5.1.1 on 2024-09-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('expiry', models.DateField()),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('LTR', 'Litre')], max_length=3)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
