# Generated by Django 5.1.1 on 2024-09-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventory')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kitchen.kitchen')),
            ],
        ),
        migrations.AddField(
            model_name='kitchen',
            name='items',
            field=models.ManyToManyField(through='Kitchen.KitchenItem', to='Inventory.inventory'),
        ),
    ]
